In [5]:
import dgl
from dgl.data.utils import load_graphs

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import random
import pandas as pd

from model.model import HTGNN, NodePredictor
from utils.pytorchtools import EarlyStopping
from utils.data import load_COVID_data, load_MAG_data, load_ML_data

dgl.seed(0)
np.random.seed(0)
torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.cuda.manual_seed_all(0)

In [8]:
original_pred = torch.tensor([1.,2.,3.,4.])
masked_pred = torch.tensor([3.,2.,5.,8.])

In [9]:
mseloss = nn.MSELoss()
l1 = F.l1_loss(original_pred, masked_pred)
l2 = torch.sqrt(mseloss(original_pred, masked_pred))

In [3]:
np.mean([1,2,3,4])

2.5

In [5]:
F.l1_loss(a,b)

tensor(2.)

In [7]:
mseloss= nn.MSELoss()
mse = mseloss(a,b)
torch.sqrt(mse)

tensor(2.4495)

In [2]:
glist, label_dict = load_graphs('data/ogbn_graphs.bin')

In [2]:
glist, label_dict = load_graphs('data/ogbn_graphs.bin')
device = torch.device('cuda')
time_window = 3

train_feats, train_labels, val_feats, val_labels, test_feats, test_labels = load_MAG_data(glist, time_window, device)


loading mp2vec
generating train, val, test sets 


In [4]:
val_feats[0]

Graph(num_nodes={'author': 17764, 'field_of_study': 23495, 'institution': 2276, 'paper': 88022},
      num_edges={('author', 'affiliated_with_t0', 'institution'): 40307, ('author', 'affiliated_with_t1', 'institution'): 40307, ('author', 'affiliated_with_t2', 'institution'): 40307, ('author', 'writes_t0', 'paper'): 244222, ('author', 'writes_t1', 'paper'): 256070, ('author', 'writes_t2', 'paper'): 235822, ('field_of_study', 'has_topic_r_t0', 'paper'): 314497, ('field_of_study', 'has_topic_r_t1', 'paper'): 310210, ('field_of_study', 'has_topic_r_t2', 'paper'): 281615, ('institution', 'affiliated_with_r_t0', 'author'): 40307, ('institution', 'affiliated_with_r_t1', 'author'): 40307, ('institution', 'affiliated_with_r_t2', 'author'): 40307, ('paper', 'cites_r_t0', 'paper'): 24416, ('paper', 'cites_r_t1', 'paper'): 25054, ('paper', 'cites_r_t2', 'paper'): 22423, ('paper', 'cites_t0', 'paper'): 24416, ('paper', 'cites_t1', 'paper'): 25054, ('paper', 'cites_t2', 'paper'): 22423, ('paper', 'ha

In [6]:
device = torch.device('cuda')
time_window = 8

train_feats_ml, train_labels_ml, val_feats_ml, val_labels_ml, test_feats_ml, test_labels_ml = load_ML_data(time_window, device)

In [7]:
train_feats_ml[0]

Graph(num_nodes={'movie': 1682, 'user': 943},
      num_edges={('movie', 'm-m_t0', 'movie'): 82798, ('movie', 'm-m_t1', 'movie'): 82798, ('movie', 'm-m_t2', 'movie'): 82798, ('movie', 'm-m_t3', 'movie'): 82798, ('movie', 'm-m_t4', 'movie'): 82798, ('movie', 'm-m_t5', 'movie'): 82798, ('movie', 'm-m_t6', 'movie'): 82798, ('movie', 'm-m_t7', 'movie'): 82798, ('movie', 'm-u_t0', 'user'): 16, ('movie', 'm-u_t1', 'user'): 5096, ('movie', 'm-u_t2', 'user'): 3731, ('movie', 'm-u_t3', 'user'): 2791, ('movie', 'm-u_t4', 'user'): 2575, ('movie', 'm-u_t5', 'user'): 2906, ('movie', 'm-u_t6', 'user'): 10794, ('movie', 'm-u_t7', 'user'): 5756, ('user', 'u-m_t0', 'movie'): 16, ('user', 'u-m_t1', 'movie'): 5096, ('user', 'u-m_t2', 'movie'): 3731, ('user', 'u-m_t3', 'movie'): 2791, ('user', 'u-m_t4', 'movie'): 2575, ('user', 'u-m_t5', 'movie'): 2906, ('user', 'u-m_t6', 'movie'): 10794, ('user', 'u-m_t7', 'movie'): 5756, ('user', 'u-u_t0', 'user'): 47150, ('user', 'u-u_t1', 'user'): 47150, ('user', 'u-u

In [10]:
train_labels_ml[0]

((tensor([195,  41, 291,  ..., 605, 787, 393], device='cuda:0'),
  tensor([241, 422, 514,  ...,  96, 327, 379], device='cuda:0')),
 (tensor([684, 559, 629,  ..., 766, 242, 746]),
  tensor([ 968, 1014,  464,  ..., 1436, 1539,  463])))

In [13]:
sg, _ = dgl.khop_in_subgraph(train_feats_ml[0], {'user': 195,'movie':241}, k=2, store_ids=True)

In [17]:
sg

Graph(num_nodes={'movie': 1009, 'user': 740},
      num_edges={('movie', 'm-m_t0', 'movie'): 36849, ('movie', 'm-m_t1', 'movie'): 36849, ('movie', 'm-m_t2', 'movie'): 36849, ('movie', 'm-m_t3', 'movie'): 36849, ('movie', 'm-m_t4', 'movie'): 36849, ('movie', 'm-m_t5', 'movie'): 36849, ('movie', 'm-m_t6', 'movie'): 36849, ('movie', 'm-m_t7', 'movie'): 36849, ('movie', 'm-u_t0', 'user'): 15, ('movie', 'm-u_t1', 'user'): 3903, ('movie', 'm-u_t2', 'user'): 3122, ('movie', 'm-u_t3', 'user'): 2408, ('movie', 'm-u_t4', 'user'): 2324, ('movie', 'm-u_t5', 'user'): 2067, ('movie', 'm-u_t6', 'user'): 9229, ('movie', 'm-u_t7', 'user'): 4791, ('user', 'u-m_t0', 'movie'): 15, ('user', 'u-m_t1', 'movie'): 3903, ('user', 'u-m_t2', 'movie'): 3122, ('user', 'u-m_t3', 'movie'): 2408, ('user', 'u-m_t4', 'movie'): 2324, ('user', 'u-m_t5', 'movie'): 2067, ('user', 'u-m_t6', 'movie'): 9229, ('user', 'u-m_t7', 'movie'): 4791, ('user', 'u-u_t0', 'user'): 28985, ('user', 'u-u_t1', 'user'): 28985, ('user', 'u-u_t

In [16]:
sg.edges(etype='m-m_t0')

(tensor([   0,    0,    0,  ..., 1008, 1008, 1008], device='cuda:0'),
 tensor([129, 101, 199,  ..., 321, 475, 698], device='cuda:0'))

In [18]:
for srctype, etype, dsttype in sg.canonical_etypes:
    src, dst = sg.edges(etype=etype)
    new_src = sg.ndata[dgl.NID][srctype][src.long()]
    new_dst = sg.ndata[dgl.NID][dsttype][dst.long()]
    break

In [23]:
new_src

tensor([   0,    0,    0,  ..., 1679, 1679, 1679], device='cuda:0')

In [54]:
device = torch.device('cuda')
glist, _ = load_graphs('data/covid_graphs.bin')
time_window = 7

train_feats, train_labels, val_feats, val_labels, test_feats, test_labels = load_COVID_data(glist, time_window)


In [56]:
glist[0]

Graph(num_nodes={'county': 3223, 'state': 51},
      num_edges={('county', 'affiliate_r', 'state'): 3141, ('county', 'nearby_county', 'county'): 22176, ('state', 'affiliate', 'county'): 3141, ('state', 'nearby_state', 'state'): 269},
      metagraph=[('county', 'state', 'affiliate_r'), ('county', 'county', 'nearby_county'), ('state', 'county', 'affiliate'), ('state', 'state', 'nearby_state')])

In [9]:
train_feats[0].nodes('state')

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       dtype=torch.int32)

In [3]:
sg, inverse_indices = dgl.khop_in_subgraph(train_feats[0], {'state': 2}, k=2, store_ids=True)

In [5]:
sg.num_edges()

13377

In [6]:
sg, inverse_indices = dgl.khop_in_subgraph(train_feats[0], {'state': [1,2]}, k=2, store_ids=True)

In [14]:
dic = {}
z = 0
# k = 0 
for stype, etype, dtype in sg.canonical_etypes:
    k = sg[stype, etype, dtype].number_of_edges()
    # k = sg[stype, etype, dtype].number_of_edges()
    dic[etype] = (z,z + k)
    z += k


In [15]:
dic

{'affiliate_r_t0': (0, 29),
 'affiliate_r_t1': (29, 58),
 'affiliate_r_t2': (58, 87),
 'affiliate_r_t3': (87, 116),
 'affiliate_r_t4': (116, 145),
 'affiliate_r_t5': (145, 174),
 'affiliate_r_t6': (174, 203),
 'nearby_county_t0': (203, 334),
 'nearby_county_t1': (334, 465),
 'nearby_county_t2': (465, 596),
 'nearby_county_t3': (596, 727),
 'nearby_county_t4': (727, 858),
 'nearby_county_t5': (858, 989),
 'nearby_county_t6': (989, 1120),
 'affiliate_t0': (1120, 1149),
 'affiliate_t1': (1149, 1178),
 'affiliate_t2': (1178, 1207),
 'affiliate_t3': (1207, 1236),
 'affiliate_t4': (1236, 1265),
 'affiliate_t5': (1265, 1294),
 'affiliate_t6': (1294, 1323),
 'nearby_state_t0': (1323, 1324),
 'nearby_state_t1': (1324, 1325),
 'nearby_state_t2': (1325, 1326),
 'nearby_state_t3': (1326, 1327),
 'nearby_state_t4': (1327, 1328),
 'nearby_state_t5': (1328, 1329),
 'nearby_state_t6': (1329, 1330)}

In [25]:
c = {type:0 for type in sg.etypes}

In [27]:
g = dgl.heterograph({
    ('user', 'plays', 'game'): (torch.tensor([0, 1, 1, 2]),
                                torch.tensor([0, 0, 1, 1])),
    ('developer', 'develops', 'game'): (torch.tensor([0, 1]),
                                        torch.tensor([0, 1]))
    })
g = dgl.remove_edges(g, torch.tensor([0, 1]), 'plays',store_ids=True)
g.edges('all', etype='plays')

(tensor([1, 2]), tensor([1, 1]), tensor([0, 1]))

In [29]:
g.num_edges()

4

In [28]:
g.edata[dgl.EID]

{('developer', 'develops', 'game'): tensor([0, 1]),
 ('user', 'plays', 'game'): tensor([2, 3])}

# GNNExplainer

In [2]:
dataset = dgl.data.CoraGraphDataset()

Extracting file to /home/jiazhengli/.dgl/cora_v2
Finished data loading and preprocessing.
  NumNodes: 2708
  NumEdges: 10556
  NumFeats: 1433
  NumClasses: 7
  NumTrainingSamples: 140
  NumValidationSamples: 500
  NumTestSamples: 1000
Done saving data into cached files.


In [13]:
dataset[0].ndata['feat'].float()

torch.Size([2708, 1433])

In [57]:
device = torch.device('cuda')
glist, _ = load_graphs('data/covid_graphs.bin')
time_window = 7

train_feats, train_labels, val_feats, val_labels, test_feats, test_labels = load_COVID_data(glist, time_window)

In [58]:
glist[0]

Graph(num_nodes={'county': 3223, 'state': 51},
      num_edges={('county', 'affiliate_r', 'state'): 3141, ('county', 'nearby_county', 'county'): 22176, ('state', 'affiliate', 'county'): 3141, ('state', 'nearby_state', 'state'): 269},
      metagraph=[('county', 'state', 'affiliate_r'), ('county', 'county', 'nearby_county'), ('state', 'county', 'affiliate'), ('state', 'state', 'nearby_state')])

In [59]:
glist[1]

Graph(num_nodes={'county': 3223, 'state': 51},
      num_edges={('county', 'affiliate_r', 'state'): 3141, ('county', 'nearby_county', 'county'): 22176, ('state', 'affiliate', 'county'): 3141, ('state', 'nearby_state', 'state'): 269},
      metagraph=[('county', 'state', 'affiliate_r'), ('county', 'county', 'nearby_county'), ('state', 'county', 'affiliate'), ('state', 'state', 'nearby_state')])

In [18]:
g = test_feats[0]
g

Graph(num_nodes={'county': 3223, 'state': 51},
      num_edges={('county', 'affiliate_r_t0', 'state'): 3141, ('county', 'affiliate_r_t1', 'state'): 3141, ('county', 'affiliate_r_t2', 'state'): 3141, ('county', 'affiliate_r_t3', 'state'): 3141, ('county', 'affiliate_r_t4', 'state'): 3141, ('county', 'affiliate_r_t5', 'state'): 3141, ('county', 'affiliate_r_t6', 'state'): 3141, ('county', 'nearby_county_t0', 'county'): 22176, ('county', 'nearby_county_t1', 'county'): 22176, ('county', 'nearby_county_t2', 'county'): 22176, ('county', 'nearby_county_t3', 'county'): 22176, ('county', 'nearby_county_t4', 'county'): 22176, ('county', 'nearby_county_t5', 'county'): 22176, ('county', 'nearby_county_t6', 'county'): 22176, ('state', 'affiliate_t0', 'county'): 3141, ('state', 'affiliate_t1', 'county'): 3141, ('state', 'affiliate_t2', 'county'): 3141, ('state', 'affiliate_t3', 'county'): 3141, ('state', 'affiliate_t4', 'county'): 3141, ('state', 'affiliate_t5', 'county'): 3141, ('state', 'affiliate

In [40]:
g.ndata['t0']['county'].shape

torch.Size([3223, 1])

In [46]:
g.ntypes

['county', 'state']

In [42]:
g.canonical_etypes

[('county', 'affiliate_r_t0', 'state'),
 ('county', 'affiliate_r_t1', 'state'),
 ('county', 'affiliate_r_t2', 'state'),
 ('county', 'affiliate_r_t3', 'state'),
 ('county', 'affiliate_r_t4', 'state'),
 ('county', 'affiliate_r_t5', 'state'),
 ('county', 'affiliate_r_t6', 'state'),
 ('county', 'nearby_county_t0', 'county'),
 ('county', 'nearby_county_t1', 'county'),
 ('county', 'nearby_county_t2', 'county'),
 ('county', 'nearby_county_t3', 'county'),
 ('county', 'nearby_county_t4', 'county'),
 ('county', 'nearby_county_t5', 'county'),
 ('county', 'nearby_county_t6', 'county'),
 ('state', 'affiliate_t0', 'county'),
 ('state', 'affiliate_t1', 'county'),
 ('state', 'affiliate_t2', 'county'),
 ('state', 'affiliate_t3', 'county'),
 ('state', 'affiliate_t4', 'county'),
 ('state', 'affiliate_t5', 'county'),
 ('state', 'affiliate_t6', 'county'),
 ('state', 'nearby_state_t0', 'state'),
 ('state', 'nearby_state_t1', 'state'),
 ('state', 'nearby_state_t2', 'state'),
 ('state', 'nearby_state_t3', 'st

In [19]:
hg = dgl.to_homogeneous(g)
hg

Graph(num_nodes=3274, num_edges=201089,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int32), '_TYPE': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int32), '_TYPE': Scheme(shape=(), dtype=torch.int64)})

In [38]:
hg.ndata[dgl.NTYPE]

tensor([0, 0, 0,  ..., 1, 1, 1])

# New dataset

In [63]:
from ogb.linkproppred import DglLinkPropPredDataset

dataset = DglLinkPropPredDataset(name = 'ogbl-collab')

split_edge = dataset.get_edge_split()
train_edge, valid_edge, test_edge = split_edge["train"], split_edge["valid"], split_edge["test"]
graph = dataset[0]

Downloaded 0.11 GB: 100%|██████████| 117/117 [00:09<00:00, 11.81it/s]


Extracting dataset/collab.zip
Loading necessary files...
This might take a while.
Processing graphs...


100%|██████████| 1/1 [00:00<00:00, 44.89it/s]


Converting graphs into DGL objects...


100%|██████████| 1/1 [00:00<00:00, 412.66it/s]

Saving...


In [64]:
graph

Graph(num_nodes=235868, num_edges=2358104,
      ndata_schemes={'feat': Scheme(shape=(128,), dtype=torch.float32)}
      edata_schemes={'year': Scheme(shape=(1,), dtype=torch.int64), 'weight': Scheme(shape=(1,), dtype=torch.int64)})

In [11]:
r = np.array([0.803 , 0.841 , 0.861 , 0.877 , 0.897 , 0.907])
np.mean(r)

0.8643333333333333

# Sentence transformer

In [1]:
from sentence_transformers import SentenceTransformer
sbert_model = SentenceTransformer('all-MiniLM-L6-v2')

/home/jiazhengli/anaconda3/envs/pt/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2023-04-21 00:07:08.698675: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-04-21 00:07:08.722251: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-21 00:07:09.065064: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find Te

In [2]:
sentences = ['i love you']

In [14]:
sentence_embeddings = sbert_model.encode(sentences)

In [7]:
movie_info = pd.read_csv('data/Movielens/movie_info.csv',sep='|',header=None)

In [8]:
movie_info

0                                          1            2   3   \
0        1                           Toy Story (1995)  01-Jan-1995 NaN   
1        2                           GoldenEye (1995)  01-Jan-1995 NaN   
2        3                          Four Rooms (1995)  01-Jan-1995 NaN   
3        4                          Get Shorty (1995)  01-Jan-1995 NaN   
4        5                             Copycat (1995)  01-Jan-1995 NaN   
...    ...                                        ...          ...  ..   
1677  1678                          Mat' i syn (1997)  06-Feb-1998 NaN   
1678  1679                           B. Monkey (1998)  06-Feb-1998 NaN   
1679  1680                       Sliding Doors (1998)  01-Jan-1998 NaN   
1680  1681                        You So Crazy (1994)  01-Jan-1994 NaN   
1681  1682  Scream of Stone (Schrei aus Stein) (1991)  08-Mar-1996 NaN   

                                                     4   5   6   7   8   9   \
0     http://us.imdb.com/M/title-exact?Toy%20Story%2...   0   0   0   1   1   
1     http://us.imdb.com/M/title-exact?GoldenEye%20(...   0   1   1   0   0   
2     http://us.imdb.com/M/title-exact?Four%20Rooms%...   0   0   0   0   0   
3     http://us.imdb.com/M/title-exact?Get%20Shorty%...   0   1   0   0   0   
4     http://us.imdb.com/M/title-exact?Copycat%20(1995)   0   0   0   0   0   
...                                                 ...  ..  ..  ..  ..  ..   
1677  http://us.imdb.com/M/title-exact?Mat%27+i+syn+...   0   0   0   0   0   
1678  http://us.imdb.com/M/title-exact?B%2E+Monkey+(...   0   0   0   0   0   
1679      http://us.imdb.com/Title?Sliding+Doors+(1998)   0   0   0   0   0   
1680  http://us.imdb.com/M/title-exact?You%20So%20Cr...   0   0   0   0   0   
1681  http://us.imdb.com/M/title-exact?Schrei%20aus%...   0   0   0   0   0   

      ...  14  15  16  17  18  19  20  21  22  23  
0     ...   0   0   0   0   0   0   0   0   0   0  
1     ...   0   0   0   0   0   0   0   1   0   0  
2     ...   0   0   0   0   0   0   0   1   0   0  
3     ...   0   0   0   0   0   0   0   0   0   0  
4     ...   0   0   0   0   0   0   0   1   0   0  
...   ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  
1677  ...   0   0   0   0   0   0   0   0   0   0  
1678  ...   0   0   0   0   0   1   0   1   0   0  
1679  ...   0   0   0   0   0   1   0   0   0   0  
1680  ...   0   0   0   0   0   0   0   0   0   0  
1681  ...   0   0   0   0   0   0   0   0   0   0  

[1682 rows x 24 columns]

In [12]:
names = []
for i in range(len(movie_info)):
    name = movie_info.iloc[i][1]
    name = name.split('(')[0][:-1]
    #print(name)
    names.append(name)
    #break

In [16]:
movie_embeddings = sbert_model.encode(names)